### ISSUE TITLE
Comparison with Microsoft.Extensions.FileSystemGlobbing

### ISSUE THREAD

**Issue by cocowalla** [kthompson/glob#16]
Now that Microsoft has a [globbing library](Microsoft.Extensions.FileSystemGlobbing), it would be useful to see a comparison of features and performance in the wiki.

**Comment by kthompson** [comment]
Hello @cocowalla there are already some examples of how this Glob library can be used in the README file. If you would like to add anything additional in the wiki I would gladly accept it.

Thanks :)
