### ISSUE TITLE
Possible bug: clarify intended behaviour of 'globstar' (**) on files in the top level directory

### ISSUE THREAD

**Issue by DavidR91** [kthompson/glob#23]
My understanding is that `**` ('globstar') matches zero or more directories (as stated in the readme)

Intuitively, this (to me) implies that a pattern like  `Dashboards/**/*.json` would bring back a file such as `Dashboards/examples/example.json` (which it does) but _also_ `Dashboards/example.json`

At least when using `.GlobFiles`, the second example does not appear to be true for this library

### Comparison with other libraries/tools
It's not totally clear to me whether this behaviour is expected - googling around, you see a mixture of behaviours for these kinds of patterns (e.g. Bash _may_ not allow these kinds of patterns without a special option being set gobally - but sometimes it does) - whereas tools such as [http://www.globtester.com/](http://www.globtester.com/) match both examples for the pattern above (which admittedly uses minimatch, and explicitly states it is [not compliant](https://github.com/isaacs/minimatch#comparisons-to-other-fnmatchglob-implementations))

What is actually the intended behaviour for globstar in this library, and/or is this a bug?

**Comment by kthompson** [comment]
It should match both `Dashboards/examples/example.json` and `Dashboards/example.json` as in your example.

**Comment by DavidR91** [comment]
Here is a small example for it:

```
using System;
using System.Collections.Generic;
using System.Linq;
using Glob;

namespace glob_testcase
{
    class Program
    {
        // glob 0.3.3
        public static void Main(string[] args)
        {
            Glob.Glob g = new Glob.Glob("dashboards/**/*.json", GlobOptions.Compiled);

            string[] files = new string[]
            {
                "dashboards/example.json",
                "dashboards/examples/example.json",
                "dashboards/toplevel.json"
            };

            IEnumerable<string> results = files.Where(f => g.IsMatch(f));

            Console.WriteLine(String.Join(", ", results));
        }
    }
}
```

Prints only:

```
dashboards/examples/example.json
```

Previously I had made mistakes with case (not realising it would understandably be case sensitive), but after correcting for that, this issue still stands.

For my use case this isn't a huge issue (I'm just auto-adding `folder/*.json` style rules automatically when globstar is detected) and I imagine this would be difficult to address without compatibility breakage 

Might just be worth a note in the readme or something for the time being though

**Comment by philpowers** [comment]
I ran into this too, and have fixed it locally by post-processing the regex that is generated within the Glob class. It was either this, or keep state in the Visitor so that '/' would not be prepended to Path Segments when immediately preceded by the Directory Wildcard.

Pull Requested created: #24
