### ISSUE TITLE
Potential false positive

### ISSUE THREAD

**Issue by fwinkelbauer** [kthompson/glob#26]
Hi,

I am wondering if the following example is a false positive or if my understanding of the library is wrong:

```csharp
var glob = new Glob("Foo.txt");
Assert.IsFalse(glob.IsMatch("SomeFoo.txt")); // this fails because IsMatch is true
```

Is this the intended behaviour?

Thanks

**Comment by kthompson** [comment]
Sorry for taking so long to respond. Looking through all of the unit tests it appears to be ambiguous as to how whether the glob should match or not. That being said, my initial thought would match yours and my expectation would be that that test would pass. I will keep this open until I have time to fix it.
