### ISSUE TITLE
sort order

### ISSUE THREAD

**Issue by xpressivecode** [kthompson/glob#29]
When traversing directories, I'm seeing unexpected sort results:
```
Root
+ barfoo 
  - 03.sql
+ foobar
  - 04.sql
-01.sql
-02.sql
```
I'm getting 01, 02, 04 and 03 back when calling Glob.GlobExtensions.GlobFiles(root, "**/*.sql") 

I would expect, 01, 02, 03 and 04?

**Comment by kthompson** [comment]
What version are you using? Directory/file traversal is mostly defined by
the underlying file system APIs.

Depending on the version you are using this may be slightly different. Ie
you may see either a breadth-first search or depth-first search.

**Comment by xpressivecode** [comment]
I included it via nuget, which appears to be version 0.4.0. 

I'm on OSX, and having used glob libs in other languages (node/Go), they return in the proper order. I don't know if those libraries are compensating behind the scenes though.

**Comment by kthompson** [comment]
I am guessing that may be the case. The code in question uses DirectoryInfo.EnumerateFiles which may be implemented differently on different platforms. 

I can probably add an option to cause sorting of files but it would reduce performance so I don't think it would be ideal to make it a default option.

**Comment by kthompson** [comment]
If it interests you to add the feature the code in question is here: https://github.com/kthompson/glob/blob/master/src/Glob/GlobExtensions.cs

**Comment by xpressivecode** [comment]
Thanks. I've gone with

```
var glob = new Glob.Glob("**/*.sql", GlobOptions.Compiled);
var files = new System.IO.DirectoryInfo(path).EnumerateFiles("*", SearchOption.AllDirectories).Where(d => glob.IsMatch(d.FullName)).OrderBy(d => d.Name);
```

This will definitely cause a hit, but I need it in the proper order. Nobody else has complained about this, so I don't know if it is worth adding an optional flag to include this feature. Appreciate the help!
