### ISSUE TITLE
Change name of Glob namespace to something else

### ISSUE THREAD

**Issue by mariuszjamro** [kthompson/glob#31]
Currently `Glob` class is inside of `Glob` namespace. This is against .NET rules [(see here)](https://blogs.msdn.microsoft.com/ericlippert/2010/03/09/do-not-name-a-class-the-same-as-its-namespace-part-one/) and makes it painful to use as you need to write:

    new Glob.Glob("pattern").

Otherwise VS gets confused that namespace is used like a type.

I propose changing the name of `Glob` namespace to `GlobExpressions` or something similar, just the same way as `Regex` class lies in `System.Text.RegularExpressions`.

Alternatively renaming of `Glob` class to `GlobPattern` would be nice alternative too.

**Comment by kthompson** [comment]
Yea I agree on this. It is something that has been an annoyance since I created the project. I will make this part of a 1.0.0 release

**Comment by kthompson** [comment]
Closed by 675c4178e40abf8f9f074ce4eaaf652207c9a775

**Comment by mariuszjamro** [comment]
Awesome! Thanks for so quick reply!
