### ISSUE TITLE
Directory.FullName path length inconsistency issue

### ISSUE THREAD

**Issue by nD3vR** [kthompson/glob#34]
Sorry I don't have a patch fix prepared but I discovered a potential bug in the latest extension methods like Glob.Files()

On my windows system Directory.FullName is not consistent in returning a string without a trailing path separator. (i.e. folders ending in a number it will add the path separator) So in some cases the truncatedLength is off by one trimming the matching string too much and not matching correctly.

It may be better to check if the path does not end with a separator before adding 1 to the truncatedLength property.

Cheers.

**Comment by kthompson** [comment]
This should be resolved in the latest master. Please let me know if you find any issue with it.
