### ISSUE TITLE
Mixing directory wildcard and identifier 

### ISSUE THREAD

**Issue by yufeih** [kthompson/glob#37]
Glob pattern `a**/*.cs` matches `a/b.cs` but also matches `a/b.md`, it should not match `a/b.md`

The correct pattern should be written as `a/**/*.cs`, but people make mistakes. 

If it is written as `a**/*.cs`, it should be interpreted as `a[Literal] *[Wildcard] *[Wildcard] /[Separator] *[Wildcard] .cs[Literal]`, and should match `ab/c.cs`, but is should not match `a/b/c.cs` or `a/b.md`

It is also valid to treat consecutive wildcards as an error if it not a directory wildcard.

**Comment by kthompson** [comment]
Yes I see what you mean. What do you think about interpreting `a**/*.cs`  as `a*/*.cs`?

I will add some tests and see what I can do.

Thanks for the report.

**Comment by yufeih** [comment]
Yes, that would be great. Thank you for the work,  this is a very nice library.

**Comment by kthompson** [comment]
It looks like this pattern would simply fail to parse at the moment. I am also considering that it would probably be closer to the intent of the user for `a**/*.cs` to be converted to `a*/**/*.cs`

**Comment by kthompson** [comment]
Seems that node's minimatch implementation is consistent with your suggestion:

```minimatch("ab/c.cs", "a**/*.cs")
true

minimatch("a/b/c.cs", "a**/*.cs")
false

minimatch("a/c.cs", "a**/*.cs")
true
```

**Comment by yufeih** [comment]
yes, I also tried that with [node-glob](https://github.com/isaacs/node-glob), it should be equivalent to `a*/*.cs`

**Comment by kthompson** [comment]
Alright sounds good. I will go with that then.
