### ISSUE TITLE
** alone does not match anything

### ISSUE THREAD

**Issue by yufeih** [kthompson/glob#38]
A possible regression due to https://github.com/kthompson/glob/commit/9e79979a9ea3048cb0c99c8153b1a1d3a5b50643, now `**` alone does not match `a` or `a/b`, `a/**` does not match `a/b/c` anymore.

`**` should be equivalent to `**/*` if it is the last segment

**Comment by kthompson** [comment]
Should be fixed in `1.0.1` thanks.
