### ISSUE TITLE
StackOverflowException when matching 'a' against 'a/**'

### ISSUE THREAD

**Issue by yufeih** [kthompson/glob#39]
An uncovered test case in https://github.com/kthompson/glob/commit/0b385038bed15dd65c89563a2e59b6e9a1d3e33e

`[InlineData("a/**", "a")]` causes `StackOverflowException`

**Comment by kthompson** [comment]
I just pushed `1.0.2` let me know if you find anything else

**Comment by yufeih** [comment]
Hi Kevin, there is another issue around this, `a/**` now matches `a` when it shouldn't.

**Comment by kthompson** [comment]
Alright I think I may have assumed that should match but it doesn't look like a few other libraries will match that. I'll take a look shortly.

-------- Original Message --------

**Comment by yufeih** [comment]
`a/*` does not match `a` in the current implementation, these two should be consistent

**Comment by kthompson** [comment]
Ok i just pushed 1.0.3 which should fix the above issue as well.

**Comment by kthompson** [comment]
I misread your comment about string.Compare, I was previously looking at that because of all the allocations but I didn't realize that overload of string.Compare existed so I was trying something else that was substantially slower. Let me try that and see how it affects performance.

**Comment by kthompson** [comment]
`1.0.4` addresses the allocations for identifiers.
