### ISSUE TITLE
A single * matches files in sub directories

### ISSUE THREAD

**Issue by yufeih** [kthompson/glob#42]
```js
> minimatch("a\\b", "*")
false
> minimatch("a", "*")
true
```

But this library produces true in both cases.

**Comment by kthompson** [comment]
Currently this is the intended behavior. If you use an expression that does not include a path separator then it is assumed that you only want to verify against the file name.

See: https://github.com/kthompson/glob/blob/master/src/Glob/Glob.cs#L49

This would probably be something that would be nice as an option.

**Comment by yufeih** [comment]
The intention is to include just the top level files, are there any other syntax that could achieve that?

**Comment by kthompson** [comment]
To match any file in any folder you would want to use a pattern like `**/*`. Using any pattern without multiple directory segments would match only on the filename. Ie `*.ba?` would only match on file name and not on the full path of file. But something like `**/*.ba?` would match in any folder for a file with that pattern.

Let me know if that doesn't make sense

**Comment by yufeih** [comment]
So if I had a file structure like this:
```
a
b
c
folder1/d
folder2/e
```
> a, b, c d, e are files, folder1 and folder2 are folders

and I would like to match just files at the top level: a, b, c but not d and e. I thought `*` could achieve that but it seems `*` matches all the files (a, b, c, d, e). I guess my question is:
1. Is there a glob that let me match just a, b, c?
2. `minimatch` matches just a, b, c with `*` in this case, does it make sense to you that we could have an option that toggles https://github.com/kthompson/glob/blob/master/src/Glob/Glob.cs#L49

**Comment by kthompson** [comment]
I don't think there is a way to only match a/b/c in this case. Let me look into adding an option.

**Comment by kthompson** [comment]
I just pushed a new version with the requested option `GlobOptions.MatchFullPath` in version `1.1.0` Let me know if that works for you.

**Comment by yufeih** [comment]
Thank you Kevin, works like a charm 👍 👍 👍

**Comment by yufeih** [comment]
@kthompson , there is a bug with how [flags](https://github.com/kthompson/glob/blob/40700cc4ea1d4a0182d21bdd57a6b51fceff63f2/src/Glob/GlobOptions.cs) are handled and it is causing our tests failing on linux.

To make enum flags work correctly, you need to manually assign a value of power of 2 like described [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/enumeration-types#enumeration-types-as-bit-flags).

**Comment by kthompson** [comment]
Ah yea... Let me push a new build.

**Comment by kthompson** [comment]
Ok new build has been pushed as 1.1.1 you can review changes here: https://github.com/kthompson/glob/compare/1.1.0...1.1.1

**Comment by yufeih** [comment]
Problem fixed. Thank you for the swift response, as always 👍
