### ISSUE TITLE
Add netstandard2.0 target

### ISSUE THREAD

**Issue by ejball** [kthompson/glob#46]
See: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

> DO include a netstandard2.0 target if you require a netstandard1.x target.

**Comment by kthompson** [comment]
I was under the impression that with .net core you wanted the lowest version number based on the APIs you need for the widest support but I wasn't aware of the dependency graph stuff. Thanks for the resource. I will go ahead and add this.
