### ISSUE TITLE
Do not include reference System.ValueTuple on Net Standard 2.0 or Net Framework 4.7

### ISSUE THREAD

**Issue by EricStG** [kthompson/glob#50]
This is obviously not a high priority item, but the reference to System.ValueTuple does not have to be included when targeting Net Standard 2.0+ or Net Framework 4.7+

https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple?view=netstandard-2.0
https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple?view=netframework-4.7

**Comment by kthompson** [comment]
If you would like to submit a PR I will look through it. Otherwise I will see if I can get to it soon.

**Comment by EricStG** [comment]
I can take a stab at it in a few days.
