### ISSUE TITLE
net 451

### ISSUE THREAD

**Issue by dazinator** [kthompson/glob#6]
Hi,

I just tried to switch to the nuget package, but as my project targets .net 451, it looks like the nuget package is incompatible.

Is it possible you could target netstandard 1.2 instead of 1.3 as I believe this would then make the library compatible with .net 451 according to this https://docs.microsoft.com/en-us/dotnet/articles/standard/library

Or if not, perhaps you could consider adding net451 as another target framework so your build produces both a netstandard 1.3 and .net 451 binaries?

**Comment by dazinator** [comment]
PR submitted!

**Comment by kthompson** [comment]
Nuget should be available now. https://www.nuget.org/packages/Glob/0.2.1 😄
