### ISSUE TITLE
Can glob handle literal negation?

### ISSUE THREAD

**Issue by brentarias** [kthompson/glob#61]
Does this tool allow providing a "not" operation for a string literal?
`**\alpha\bravo\*\foo.{!doc,!docx}`
...or perhaps the same idea...
`**\alpha\bravo\*\foo.{^doc,^docx}`
If yes, could you include that in the documentation?  If no, could you add that feature?

**Comment by kthompson** [comment]
Hello @brentarias. This library does not currently support extended globbing patterns. I don't have any immediate plans to add support for this either. I would be open to a pull request though :)

**Comment by kthompson** [comment]
Closing this issue at this time.
