### ISSUE TITLE
Add GlobOptions to Extension Methods in GlobExtensions.cs

### ISSUE THREAD

**Issue by VolkmarR** [kthompson/glob#63]
The three extension methods in GlobExtensions.cs currently don't provide a parameter to specify GlobOptions. 

I could provide a PR if you like, where I change the method declaration to 

    public static IEnumerable<DirectoryInfo> GlobDirectories(this DirectoryInfo di, string pattern, GlobOptions options = GlobOptions.none)

**Comment by VolkmarR** [comment]
Hi @kthompson ... i added the overloads. Should I also add unit tests?

https://github.com/VolkmarR/glob/tree/Extensions-GlobOptions

**Comment by kthompson** [comment]
> Hi @kthompson ... i added the overloads. Should I also add unit tests?
> 
> 
> 
> https://github.com/VolkmarR/glob/tree/Extensions-GlobOptions

That would be great 👍

**Comment by VolkmarR** [comment]
I added 3 tests

**Comment by kthompson** [comment]
Please make a pull request and I will review 👏

**Comment by kthompson** [comment]
Addressed in PR https://github.com/kthompson/glob/pull/64

Included in release 1.1.9

Thanks!
