### ISSUE TITLE
Negating patterns (bash-like) not functioning

### ISSUE THREAD

**Issue by lkallas** [kthompson/glob#84]
Related to [another issue](https://github.com/Contrast-Security-OSS/agent-operator/issues/189) 

It seems that negating patterns are not fully supported, especially this negating one supported by bash:

```sh
!(pattern-list)
Matches anything except one of the given patterns in brackets.
```

Refer to the linked issue to get the snippet of code for illustration and testing of the issue.

**Comment by kthompson** [comment]
Thats right no extended glob expressions are supported currently.

**Comment by lkallas** [comment]
Thank you!
I think it would be beneficial to mention it in README that there is no extended glob expression support currently.

Closing this issue.
